---
version: 2.1

commands:
  test:
    steps:
      - checkout

      # Restore Cached Dependencies
      - restore_cache:
          name: Restore bundle cache
          key: oddball-fitness-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle

      # Cache Dependencies
      - save_cache:
          name: Store bundle cache
          key: oddball-fitness-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - oddball-fitness-yarn-{{ checksum "yarn.lock" }}
            - oddball-fitness-yarn-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
      - save_cache:
          key: oddball-fitness-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      - run: cp ./config/database.yml.ci ./config/database.yml

      # Setup the database
      - run: bin/rails db:schema:load --trace

      - run:
          name: Run tests in parallel
          command: bundle exec rails test $(circleci tests glob "test/**/*_test.rb" | circleci tests split --split-by=timings)

      - run:
          name: Run test:system in parallel
          command: bundle exec rails test:system $(circleci tests glob "test/system/*_test.rb" | circleci tests split --split-by=timings)

      - store_test_results:
          path: test_results

  deploy:
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
            heroku run rake db:migrate --app $HEROKU_APP_NAME

default_job: &default_job
  working_directory: ~/oddball-fitness
  steps:
    - test
    - deploy

jobs:
  ruby-26:
    <<: *default_job
    docker:
      - image: circleci/ruby:2.6.5-node-browsers-legacy
        environment:
          PGHOST: localhost
          PGUSER: oddball_fitness
          PGPASS: "0ddb@ll"
          PGDB: oddball_fitness_test
          RAILS_ENV: test
      - image: postgres:10.1-alpine
        environment:
          POSTGRES_USER: oddball_fitness
          POSTGRES_DB: oddball_fitness_test
          POSTGRES_PASSWORD: "0ddb@ll"

workflows:
  version: 2
  TD:
    jobs:
      - ruby-26
